language: cpp

os: 
  - osx
  - linux 

env:
    matrix:
        - PYTHON_EXE="`which python2`"
        - PYTHON_EXE="`which python3.4`"
        - PYTHON_EXE="`which python3.5`"

install:
    - PYTHON_EXE=$PYTHON_EXE ./configure

script:
    - "bin/py.test -vvs"

notifications:
    irc:
        channels:
          - "chat.freenode.net#aboutcode"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} : %{build_url}"
