language: generic

os:
    - osx
    - linux

env:
    matrix:
        - PYENV_VERSION='3.6.1' NODE_VERSION='6.11.2'  PYENV_VERSION_STRING='Python 3.6.1'
#       - PYENV_VERSION='3.5.3' NODE_VERSION='8.4.0'   PYENV_VERSION_STRING='Python 3.5.3'

before_install:
    - nvm install ${NODE_VERSION} && nvm use ${NODE_VERSION}
    - source setup-pyenv.sh

install:
    - pyenv install --list
    - npm install
    - ./configure
    - ./configure ./etc/conf/dev/transpile
    - ./bin/python transpile/transpile.py

before_script:
    - bin/pip install aboutcode-toolkit
    - bin/about-code check --show-all .

script:
    - ./bin/py.test -vvs
    - npm test

notifications:
    irc:
      channels:
        - "chat.freenode.net#aboutcode"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} : %{build_url}"
