version: '{build}'

environment:
    matrix:
        - PYTHON_EXE: "C:\\Python36\\python.exe"
        - PYTHON_EXE: "C:\\Python36-x64\\python.exe"

install:
    - configure

build: off

test_script:
    - 'bin\activate'
    - 'bin\python -c "from __future__ import print_function;import sys;print(sys.getdefaultencoding())"'
    - 'bin\py.test -vvs'

