# See also https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/cross-platform-scripting?view=azure-devops&tabs=yaml
trigger:
    branches:
        include: ['*']
    tags:
        include: ['*']

pr:
    branches:
        include: ['*']

jobs:
#    - template: etc/ci/azure-posix.yml
#      parameters:
#          name: Ubuntu_16
#          image_name: ubuntu-16.04
#          matrix:
#              Python_27_Linux:
#                  python_version: '2.7'
#              Python_36_Linux:
#                  python_version: '3.6'
#              Python_37_Linux:
#                  python_version: '3.7'
#
#    - template: etc/ci/azure-posix.yml
#      parameters:
#          name: macOS_1013
#          image_name: macos-10.13
#          matrix:
#              Python_27_Mac:
#                  python_version: '2.7'
#              Python_36_Mac:
#                  python_version: '3.6'
#              Python_37_Mac:
#                  python_version: '3.7'
#
#    - template: etc/ci/azure-posix.yml
#      parameters:
#          name: macOS_1014
#          image_name: macos-10.14
#          matrix:
#              Python_27_Mac:
#                  python_version: '2.7'
#              Python_36_Mac:
#                  python_version: '3.6'
#              Python_37_Mac:
#                  python_version: '3.7'
#
#    - template: etc/ci/azure-win.yml
#      parameters:
#          name: Windows_2016_32
#          image_name: vs2017-win2016
#          matrix:
#              Python_27_Win32:
#                  python_version: '2.7'
#                  python_architecture: 'x86'
#              Python_36_Win32:
#                  python_version: '3.6'
#                  python_architecture: 'x86'
#              Python_37_Win32:
#                  python_version: '3.7.3'
#                  python_architecture: 'x86'
#
#    - template: etc/ci/azure-win.yml
#      parameters:
#          name: Windows_2016_64
#          image_name: vs2017-win2016
#          matrix:
#              Python_27_Win64:
#                  python_version: '2.7'
#                  python_architecture: 'x64'
#              Python_36_Win64:
#                  python_version: '3.6' 
#                  python_architecture: 'x64'
#              Python_37_Win64:
#                  python_version: '3.7'
#                  python_architecture: 'x64'


    - template: etc/ci/azure-container.yml
      parameters:
          name: CentOS7_plain
          container: 'centos:7'
          python_version: '2.7'
          package_manager: yum 
          test_command: 'sudo yum update'

    - template: etc/ci/azure-container.yml
      parameters:
          name: Debian_9
          container: 'debian:stretch'
          python_version: '2.7'
          package_manager: apt-get
          test_command: 'sudo apt-get update'




#    - template: etc/ci/azure-container.yml
#      parameters:
#          name: CentOS7_py27
#          container: 'centos/python-27-centos7:latest'
#          python_version: '2.7'
#
#    - template: etc/ci/azure-container.yml
#      parameters:
#          name: CentOS7_py36
#          container: 'centos/python-36-centos7:latest'
#          python_version: '3.6'
#
#    - template: etc/ci/azure-container.yml
#      parameters:
#          name: Fedora_30_py27
#          container: 'fedora:30'
#          python_version: '2.7'
#          install_packages: |
#              yum update -y
#              yum groupinstall -y 'development tools'
#              yum install -y epel-release
#              yum install -y \
#                  gcc \
#                  openssl openssl-devel \
#                  sqlite-devel zlib-dev xz-devel bzip2-devel \
#                  bzip2 tar unzip zip \
#                  libxml2-devel libxslt-devel \
#                  python27-devel
#
#    - template: etc/ci/azure-container.yml
#      parameters:
#          name: Fedora_30_py36
#          container: 'fedora:30'
#          python_version: '3.6'
#          install_packages: |
#              yum update -y
#              yum groupinstall -y 'development tools'
#              yum install -y epel-release
#              yum install -y \
#                  gcc \
#                  openssl openssl-devel \
#                  sqlite-devel zlib-dev xz-devel bzip2-devel \
#                  bzip2 tar unzip zip \
#                  libxml2-devel libxslt-devel \
#                  python36 python36-devel
#
#
#    - template: etc/ci/azure-container.yml
#      parameters:
#          name: Ubuntu14_Trusty_py27
#          container: 'ubuntu:trusty'
#          python_version: '2.7'
#          install_packages: |
#              apt-get -y install software-properties-common
#              add-apt-repository -y ppa:deadsnakes
#              apt-get -y update
#              apt-get -y upgrade
#              apt-get -y \
#                  build-essential \
#                  xz-utils zlib1g bzip2 tar \
#                  libxml2-dev libxslt1-dev \
#                  python python-dev
#
#    - template: etc/ci/azure-container.yml
#      parameters:
#          name: Ubuntu14_Trusty_py36
#          container: 'ubuntu:trusty'
#          python_version: '3.6'
#          install_packages: |
#              apt-get -y install software-properties-common
#              add-apt-repository -y ppa:deadsnakes
#              apt-get -y update
#              apt-get -y upgrade
#              apt-get -y \
#                  build-essential \
#                  xz-utils zlib1g bzip2 tar \
#                  libxml2-dev libxslt1-dev \
#                  python3.6 python3.6-venv python3.6-dev
#
#    - template: etc/ci/azure-container.yml
#      parameters:
#          name: Ubuntu16_Xenial_py27
#          container: 'ubuntu:xenial'
#          python_version: '2.7'
#          install_packages: |
#              apt-get -y install software-properties-common
#              add-apt-repository -y ppa:deadsnakes
#              apt-get -y update
#              apt-get -y upgrade
#              apt-get -y \
#                  build-essential \
#                  xz-utils zlib1g bzip2 tar \
#                  libxml2-dev libxslt1-dev \
#                  python python-dev
#
#    - template: etc/ci/azure-container.yml
#      parameters:
#          name: Ubuntu16_Xenial_py36
#          container: 'ubuntu:xenial'
#          python_version: '3.6'
#          install_packages: |
#              apt-get -y install software-properties-common
#              add-apt-repository -y ppa:deadsnakes
#              apt-get -y update
#              apt-get -y upgrade
#              apt-get -y \
#                  build-essential \
#                  xz-utils zlib1g bzip2 tar \
#                  libxml2-dev libxslt1-dev \
#                  python3.6 python3.6-venv python3.6-dev
#
#
#    - template: etc/ci/azure-container.yml
#      parameters:
#          name: Ubuntu_18_Bionic_py27
#          container: 'ubuntu:bionic'
#          python_version: '2.7'
#          install_packages: |
#              apt-get -y install software-properties-common
#              add-apt-repository -y ppa:deadsnakes
#              apt-get -y update
#              apt-get -y upgrade
#              apt-get -y \
#                  build-essential \
#                  xz-utils zlib1g bzip2 tar \
#                  libxml2-dev libxslt1-dev \
#                  python python-dev
#
#    - template: etc/ci/azure-container.yml
#      parameters:
#          name: Ubuntu_18_Bionic_py36
#          container: 'ubuntu:bionic'
#          python_version: '3.6'
#          install_packages: |
#              apt-get -y install software-properties-common
#              add-apt-repository -y ppa:deadsnakes
#              apt-get -y update
#              apt-get -y upgrade
#              apt-get -y \
#                  build-essential \
#                  xz-utils zlib1g bzip2 tar \
#                  libxml2-dev libxslt1-dev \
#                  python3.6 python3.6-venv python3.6-dev
#
#
#    - template: etc/ci/azure-container.yml
#      parameters:
#          name: Debian_9_Stretch_py27
#          container: 'debian:stretch'
#          python_version: '2.7'
#          install_packages: |
#              apt-get -y update
#              apt-get -y upgrade
#              apt-get -y \
#                  build-essential \
#                  xz-utils zlib1g libbz2-1.0 tar \
#                  libxml2-dev libxslt1-dev \
#                  python python-dev
#
#    - template: etc/ci/azure-container.yml
#      parameters:
#          name: Debian_9_Stretch_py36
#          container: 'debian:stretch'
#          python_version: '3.6'
#          install_packages: |
#              apt-get -y update
#              apt-get -y upgrade
#              apt-get -y \
#                  build-essential \
#                  xz-utils zlib1g libbz2-1.0 tar \
#                  libxml2-dev libxslt1-dev
#              # install from testing
#              echo "" >> /etc/apt/sources.list
#              echo "deb http://ftp.de.debian.org/debian testing main" >> /etc/apt/sources.list
#              echo 'APT::Default-Release "stable";' | tee -a /etc/apt/apt.conf.d/00local
#              apt-get -t testing install python3.6 python3.6-dev
#
#
#    - template: etc/ci/azure-container.yml
#      parameters:
#          name: Manylinux1_686
#          container: 'quay.io/pypa/manylinux1_i686:latest'
#          python_version: '2.7'
#
#    - template: etc/ci/azure-container.yml
#      parameters:
#          name: Manylinux1_64
#          container: 'quay.io/pypa/manylinux1_x86_64:latest'
#          python_version: '2.7'
