# See also https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/cross-platform-scripting?view=azure-devops&tabs=yaml
trigger:
    branches:
        include: ['*']
    tags:
        include: ['*']

jobs:
    - template: etc/ci/azure-all.yml
      parameters:
          name: Linux
          image_name: ubuntu-16.04
          matrix:
              Python_27_Linux:
                  python_version: '2.7'
              Python_36_Linux:
                  python_version: '3.6'
              Python_37_Linux:
                  python_version: '3.7'
    
    - template: etc/ci/azure-all.yml
      parameters:
          name: macOS
          image_name: macos-10.13
          matrix:
              Python_27_Mac:
                  python_version: '2.7'
              Python_36_Mac:
                  python_version: '3.6'
              Python_37_Mac:
                  python_version: '3.7'
    
    - template: etc/ci/azure-all.yml
      parameters:
          name: Windows
          image_name: vs2017-win2016
          matrix:
              Python_27_Win:
                  python_version: '2.7'
              Python_36_Windows:
                  python_version: '3.6'
              Python_37_Windows:
                  python_version: '3.7'
