parameters:
  name: ''
  container: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}

  pool: 
    vmImage: 'ubuntu-16.04'

  container: ${{ parameters.container }}

  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:

    - script |
       echo "Python $(python_version)"
       uname -a
       which python
       which python2
       which python3
       which python$(python_version)
