parameters:
  name: ''
  image_name: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}

  pool: 
    vmImage: ${{ parameters.image_name }}

  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:

    - task: UsePythonVersion@0
      inputs:
          versionSpec: '$(python_version)'
          architecture: 'x64'

    - script: configure,abt
      displayName: 'Configure'
    - script: dir bin && dir Scripts && dir
      displayName: 'Check ABOUT files'
    - script: bin\py.test.exe -vvs
      displayName: 'Run tests'