parameters:
  name: ''
  container: ''
  python_version: ''
  package_manager: ''
  required_packages: ''

jobs:
- job: ${{ parameters.name }}

  pool: 
    vmImage: 'ubuntu-16.04'

  container:
    image: ${{ parameters.container }}
    options: '--name ${{ parameters.name }} -v /usr/bin/docker:/tmp/docker:ro'

  steps:
    - script: /tmp/docker exec -t -u 0 ${{ parameters.name }} $(Build.SourcesDirectory)/etc/ci/install_sudo.sh ${{ parameters.package_manager }}
      displayName: Install sudo
    - script: sudo ${{ parameters.package_manager }} install -y ${{ parameters.required_packages }}
      displayName: Install required packages
    - script: |
       set -ex
       echo "Testing with Python ${{ parameters.python_version }}"
       uname -a
       
       