parameters:
  name: ''
  container: ''
  python_version: ''
  test_command: ''

jobs:
- job: ${{ parameters.name }}

  pool: 
    vmImage: 'ubuntu-16.04'

  container:
    image: ${{ parameters.container }}
    options: -u root

  steps:
    - script: |
       set -ex
       whoami
       echo "Testing with Python ${{ parameters.python_version }}"
       uname -a
       ${{ parameters.test_command }}
       
       