parameters:
  name: ''
  container: ''
  python_version: ''

jobs:
- job: ${{ parameters.name }}

  pool: 
    vmImage: 'ubuntu-16.04'

  container: ${{ parameters.container }}

  steps:
    - script: |
       echo "Testing with Python ${{ parameters.python_version }}"
       uname -a
       python --version
       