parameters:
  name: ''
  image_name: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}

  pool: 
    vmImage: ${{ parameters.image_name }}

  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:

    - task: UsePythonVersion@0
      inputs:
          versionSpec: '$(python_version)'
          architecture: 'x64'

    - script: |
        configure.bat
        bin\about-code check --verbose .
        bin\py.test -vvs
      displayName: 'Run tests'
      failOnStderr: true
