parameters:
    name: ''
    container: ''
    matrix: []

jobs:
  - job: ${{ parameters.name }}
    pool: 
        vmImage: vmImage: 'ubuntu-16.04'
    container: ${{ parameters.container }}

    strategy:
        matrix:
            ${{ insert }}: ${{ parameters.matrix }}

    steps:
#      - task: UsePythonVersion@0
#        inputs:
#            versionSpec: '$(python_version)'

#            architecture: 'x64'

      - script echo $(python_version)
      - script: which python2
      - script: which python3
      - script: uname -a
  