parameters:
  name: ''
  container: ''
  python_version: ''


jobs:
- job: ${{ parameters.name }}

  pool: 
    vmImage: 'ubuntu-16.04'

  container: ${{ parameters.container }}

  steps:
    - script: |
       echo "Python ${{ parameters.python_version }}"
       uname -a
       which python
       which python2
       which python3
       which python${{ parameters.python_version }}
