parameters:
  name: ''
  container: ''
  python_version: ''
  package_manager: ''
  test_command: ''

jobs:
- job: ${{ parameters.name }}

  pool: 
    vmImage: 'ubuntu-16.04'

  container:
    image: ${{ parameters.container }}
    options: '--name ${{ parameters.name }} -v /usr/bin/docker:/tmp/docker:ro'

  steps:
    - script: /tmp/docker exec -t -u 0 ${{ parameters.name }} $(Build.SourcesDirectory)/etc/ci/install_sudo.sh ${{ parameters.package_manager }}
    - script: |
       set -ex
       whoami
       echo "Testing with Python ${{ parameters.python_version }}"
       uname -a
       ${{ parameters.test_command }}
       
       